export const products = [
    {
        id: 1,
        name: "edozie",
        task1: 10,
        task2: 10,
        task3: 10,
        grade: 92.54,
    },
    {
        id: 2,
        name: "obi",
        task1: 10,
        task2: 10,
        task3: 10,
        grade: 99.2,
    },
    {
        id: 3,
        name: "emma",

        task1: 10,
        task2: 10,
        task3: 10,
        grade: 98.32,
    },
    {
        id: 4,
        name: "chisom",
        task1: 10,
        task2: 10,
        task3: 10,
        grade: 81.34,
    },
]

export const frontend = [
    {
        id: 1,
        name: "chioma",
        task1: 8,
        task2: 9,
        task3: 9,
        grade: 89.2,
    },
    {
        id: 2,
        name: "chika",
        task1: 10,
        task2: 3.8,
        task3: 8,
        grade: 70.8,
    },
    {
        id: 3,
        name: "okey",
        task1: 5,
        task2: 3,
        task3: 10,
        grade: 60,
    },
    {
        id: 4,
        name: "Andrew",
        task1: 2,
        task2: 3,
        task3: 5,
        grade: 50,
    },
    {
        id: 5,
        name: "Anselem",
        task1: 1,
        task2: 1.5,
        task3: 8,
        grade: 50,
    },
]
export const backend = [
    {
        id: 1,
        name: "Phillip",
        task1: 10,
        task2: 7,
        task3: 9,
        grade: 90,
    },
    {
        id: 2,
        name: "Humphrey",
        task1: 8,
        task2: 6,
        task3: 9,
        grade: 80.9,
    },
    {
        id: 3,
        name: "Sylvia",
        task1: 6,
        task2: 7,
        task3: 7,
        grade: 80,
    },
    {
        id: 4,
        name: "felicia",
        task1: 8,
        task2: 9,
        task3: 5,
        grade: 78.1,
    },
    {
        id: 5,
        name: "brandon",
        task1: 10,
        task2: 0,
        task3: 10,
        grade: 70,
    },
]
export const web3 = [
    {
        id: 1,
        name: "Shola",
        task1: 10,
        task2: 7,
        task3: 9,
        grade: 90,
    },
    {
        id: 2,
        name: "Indabosky",
        task1: 9,
        task2: 5,
        task3: 9,
        grade: 80.2,
    },
    {
        id: 3,
        name: "Blossom",
        task1: 4,
        task2: 7,
        task3: 4,
        grade: 70,
    },
    {
        id: 4,
        name: "Israel",
        task1: 8,
        task2: 10,
        task3: 7,
        grade: 79.9,
    },
    {
        id: 5,
        name: "brandon",
        task1: 10,
        task2: 2,
        task3: 10,
        grade: 72,
    },
]